databendlabs/databend-jdbc

README.md
databend-client/pom.xml
databend-jdbc/pom.xml
databend-jdbc/src/main/java/com/databend/jdbc/DatabendConnection.java
databend-jdbc/src/main/java/com/databend/jdbc/DatabendDatabaseMetaData.java
databend-jdbc/src/main/java/com/databend/jdbc/DatabendPreparedStatement.java
databend-jdbc/src/test/java/com/databend/jdbc/TestBasicDriver.java
databend-jdbc/src/test/java/com/databend/jdbc/TestDatabendDatabaseMetaData.java
pom.xml

Release note:
1. fix jdbc url parsing bugs 
2. fix DatabaseMetadata for column and its type representation

feat: release databend-jdbc:0.0.3

---

databend-client/pom.xml
databend-client/src/main/java/com/databend/client/PaginationOptions.java
databend-jdbc/pom.xml
databend-jdbc/src/main/java/com/databend/jdbc/ConnectionProperties.java
databend-jdbc/src/main/java/com/databend/jdbc/ConnectionProperty.java
databend-jdbc/src/main/java/com/databend/jdbc/DatabendConnection.java
databend-jdbc/src/main/java/com/databend/jdbc/DatabendDriverUri.java
databend-jdbc/src/main/java/com/databend/jdbc/DatabendPreparedStatement.java
databend-jdbc/src/main/java/com/databend/jdbc/cloud/DatabendPresignClient.java
databend-jdbc/src/main/java/com/databend/jdbc/cloud/DatabendPresignClientV1.java
databend-jdbc/src/test/java/com/databend/jdbc/TestBasicDriver.java
databend-jdbc/src/test/java/com/databend/jdbc/TestDatabendDriverUri.java
databend-jdbc/src/test/java/com/databend/jdbc/TestFileTransfer.java
databend-jdbc/src/test/java/com/databend/jdbc/TestPrepareStatement.java
databend-jdbc/src/test/java/com/databend/jdbc/cloud/TestDatabendPresignClient.java
docs/Connection.md
pom.xml

Support the following jdbc properties
- User
- Password
- ssl
- presigned_url_disabled
- wait_time_secs 
- max_rows_in_buffer
- max_rows_per_page
Support to use presign api when presigned_url_disabled option is true

Feat: Support jdbc properties

---

databend-jdbc/src/main/java/com/databend/jdbc/AbstractDatabendResultSet.java
databend-jdbc/src/main/java/com/databend/jdbc/ColumnInfo.java
databend-jdbc/src/main/java/com/databend/jdbc/ConnectionProperties.java
databend-jdbc/src/main/java/com/databend/jdbc/DatabendColumnInfo.java
databend-jdbc/src/main/java/com/databend/jdbc/DatabendResultSetMetaData.java

There classes need to exported.

fix: export class

---

databend-client/src/main/java/com/databend/client/StageAttachment.java
databend-jdbc/src/main/java/com/databend/jdbc/DatabendPreparedStatement.java

Add default file_format for stage attachment

fix: add file_format for stage attachment

---

databend-jdbc/src/main/java/com/databend/jdbc/cloud/DatabendPresignClientV1.java

This reverts commit fecf582add335571bac320ef827d6a72e978fc2e.

Revert "fix write hang"

---

databend-client/pom.xml
databend-jdbc/pom.xml
databend-jdbc/src/main/java/com/databend/jdbc/DatabendDatabaseMetaData.java
pom.xml

- add dependencies for databend-client and databend-jdbc
- fix where SQL field

fix: support dbeaver

---

databend-client/pom.xml
databend-jdbc/pom.xml

- Upgrade okhttp version to fix hang

fix: upgrade okhttp version

---

databend-client/pom.xml
databend-jdbc/pom.xml
pom.xml

1. resolve network issue on okhttp using 5.0.0-alpha11 patch https://github.com/square/okhttp/issues/7530#issuecomment-1371536819
2. Support tableau
3. Bug fixes

feat: release jdbc 0.0.8 

---

databend-jdbc/src/main/java/com/databend/jdbc/DatabendConnection.java

Fix https://github.com/datafuselabs/databend/discussions/11623

fix: disable presign flag bug

---

databend-client/pom.xml
databend-jdbc/pom.xml
pom.xml

Changelog:
Support for debezium server
Support Flink CDC

release 0.1.0

---

README.md
databend-client/pom.xml
databend-jdbc/pom.xml
pom.xml

Support bring client-side query id to jdbc driver

feat: release v0.1.2

---

.github/workflows/test.yml

Now test CI has error like "{"error":{"code":"401","message":"No authorization header detected"}}", fix it.

fix: ci test step

---

databend-jdbc/src/main/java/com/databend/jdbc/DatabendStatement.java
databend-jdbc/src/test/java/com/databend/jdbc/TestBasicDriver.java

Fix https://github.com/datafuselabs/databend-jdbc/issues/102

fix: override method error

---

databend-jdbc/src/main/java/com/databend/jdbc/examples/Examples.java
databend-jdbc/src/test/java/com/databend/jdbc/TestPrepareStatement.java
examples/Examples.java

- Add `examples` dir
- More tests
- Fix https://github.com/datafuselabs/databend-jdbc/issues/107

fix: add examples and more tests

---

.github/workflows/release_jar_to_github.yml

Fix https://github.com/datafuselabs/databend-jdbc/issues/126

feat: add ci to release jdbc jar

---

databend-client/src/main/java/com/databend/client/data/DatabendDataType.java
databend-client/src/main/java/com/databend/client/data/DatabendTypes.java
databend-jdbc/pom.xml
databend-jdbc/src/main/java/com/databend/jdbc/ConnectionProperties.java
databend-jdbc/src/main/java/com/databend/jdbc/DatabendConnection.java
databend-jdbc/src/main/java/com/databend/jdbc/DatabendDriverUri.java
databend-jdbc/src/main/java/com/databend/jdbc/DatabendPreparedStatement.java
databend-jdbc/src/test/java/com/databend/jdbc/TestDatabendDriverUri.java
databend-jdbc/src/test/java/com/databend/jdbc/TestPrepareStatement.java
docs/Connection.md

- Support binary type
- Add binary_format options in file_format_options

feat: support binary and binary_format options

---

databend-jdbc/src/main/java/com/databend/jdbc/DatabendPreparedStatement.java

- setObject not return when handle `null`

fix: setObject null type

---

databend-jdbc/src/main/java/com/databend/jdbc/ConnectionProperties.java
databend-jdbc/src/main/java/com/databend/jdbc/DatabendDriverUri.java
databend-jdbc/src/main/java/com/databend/jdbc/DatabendPreparedStatement.java
databend-jdbc/src/test/java/com/databend/jdbc/TestPrepareStatement.java

- refactor build stageAttachement
- add some tests

chore: refactor build stageAttachment

---

.github/workflows/release_jar_to_github.yml

skiptests  in workflow when release jar

fix: skiptests when release jar

---

databend-client/src/main/java/com/databend/client/ClientSettings.java
databend-jdbc/src/main/java/com/databend/jdbc/ConnectionProperties.java
databend-jdbc/src/main/java/com/databend/jdbc/DatabendConnection.java
databend-jdbc/src/main/java/com/databend/jdbc/DatabendDriverUri.java
databend-jdbc/src/test/java/com/databend/jdbc/TestDatabendDriverUri.java

- Add `warehouse` param in driver property.

feat: add warehouse and tenant param in driver property

---

databend-client/src/main/java/com/databend/client/DatabendClientV1.java
databend-jdbc/src/main/java/com/databend/jdbc/AbstractDatabendResultSet.java
databend-jdbc/src/main/java/com/databend/jdbc/ConnectionProperties.java
databend-jdbc/src/main/java/com/databend/jdbc/DatabendConnection.java
databend-jdbc/src/main/java/com/databend/jdbc/DatabendDatabaseMetaData.java
databend-jdbc/src/main/java/com/databend/jdbc/DatabendDriverUri.java
databend-jdbc/src/main/java/com/databend/jdbc/NonRegisteringDatabendDriver.java
databend-jdbc/src/test/java/com/databend/jdbc/TestBasicDriver.java
databend-jdbc/src/test/java/com/databend/jdbc/TestDatabendDatabaseMetaData.java
databend-jdbc/src/test/java/com/databend/jdbc/TestDatabendDriverUri.java

- Now the SQL NULL value will be got as  java string `NULL`, this pr fix the SQL NULL return as java NULL.
- Add ping when getConnection so that can throw exception as soon as possible when the server can't be reached

fix: get null value

---

README.md
databend-client/pom.xml
databend-jdbc/pom.xml
pom.xml

- Add `strnullasnull` param to handle java null value
- Ping the server when create jdbc connection https://github.com/datafuselabs/databend-jdbc/pull/142
- Add `sslmode` in dsn param https://github.com/datafuselabs/databend-jdbc/pull/141

feat: release v0.1.7

---

README.md
databend-client/pom.xml
databend-jdbc/pom.xml
pom.xml

Release Note:
- fix: setString when prepare select stmt https://github.com/datafuselabs/databend-jdbc/pull/145

feat: release v0.1.8

---

databend-jdbc/src/main/java/com/databend/jdbc/DatabendDatabaseMetaData.java

Fix https://github.com/datafuselabs/databend-jdbc/issues/152

fix: type_name in getColumnsMetaDataBySQL

---

databend-jdbc/src/main/java/com/databend/jdbc/DatabendPreparedStatement.java
databend-jdbc/src/test/java/com/databend/jdbc/TestPrepareStatement.java

feat: support MyBatis

---

README.md
databend-client/pom.xml
databend-jdbc/pom.xml
pom.xml

Release Note:
- fix: setString for merge https://github.com/datafuselabs/databend-jdbc/pull/151
- fix: type_name in getColumnsMetaDataBySQL https://github.com/datafuselabs/databend-jdbc/pull/154
- fix: setNull when executeUpdate https://github.com/datafuselabs/databend-jdbc/pull/157
- feat: support compress data when uploadStream https://github.com/datafuselabs/databend-jdbc/pull/155
- feat: support MyBatis https://github.com/datafuselabs/databend-jdbc/pull/159

feat: release 0.1.9

---

databend-client/src/main/java/com/databend/client/DatabendSession.java
databend-client/src/test/java/com/databend/client/TestQueryResults.java

1.  `keep_server_session_secs` is not expected to be used.
2.  current impl send `keepServerSessionSecs` instead of  `keep_server_session_secs` , which is ignored

fix: remove unused field `getKeepServerSessionSecs`.

---

databend-client/src/main/java/com/databend/client/data/ColumnTypeHandlerFactory.java
databend-client/src/main/java/com/databend/client/data/Int8Handler.java
databend-jdbc/src/test/java/com/databend/jdbc/TestDatabendDatabaseMetaData.java

The returned result type must be the same as the database query type

mybatis supports decimal types

---

databend-jdbc/src/main/java/com/databend/jdbc/DatabendStatement.java

fix: remove checks in updateClientSession.

---

databend-jdbc/src/main/java/com/databend/jdbc/DatabendStatement.java
databend-jdbc/src/test/java/com/databend/jdbc/TestBasicDriver.java

- fix updateCount when execute
- add some merge into tests

fix: updateCount in some execute

---

databend-jdbc/src/main/java/com/databend/jdbc/DatabendConnection.java
databend-jdbc/src/main/java/com/databend/jdbc/exception/DatabendFailedToPingException.java

Fix https://github.com/datafuselabs/databend-jdbc/issues/165

fix: more ping server failed message

---

databend-jdbc/src/main/java/com/databend/jdbc/DatabendPreparedStatement.java
databend-jdbc/src/test/java/com/databend/jdbc/TestPrepareStatement.java

Fix https://github.com/datafuselabs/databend-jdbc/issues/166

fix: setvalue with quote

---

databend-client/src/main/java/com/databend/client/DatabendClientV1.java
databend-client/src/main/java/com/databend/client/DatabendSession.java
databend-client/src/main/java/com/databend/client/ServerInfo.java
databend-jdbc/src/main/java/com/databend/jdbc/DatabendConnection.java
databend-jdbc/src/test/java/com/databend/jdbc/TestTransaction.java

- part of https://github.com/datafuselabs/databend/issues/14789

feat: support transaction

---

databend-client/src/main/java/com/databend/client/DatabendClient.java
databend-client/src/main/java/com/databend/client/DatabendClientV1.java
databend-jdbc/src/main/java/com/databend/jdbc/DatabendResultSet.java
databend-jdbc/src/main/java/com/databend/jdbc/DatabendStatement.java

a fix by the way: `state = succeeded ` but maybe there are still data to fetch.

feat: ResultSet wait until schema is ready.

---

README.md
databend-client/pom.xml
databend-jdbc/pom.xml
pom.xml

- feat: support transaction  https://github.com/datafuselabs/databend-jdbc/pull/168
- fix: ResultSet wait until schema is ready https://github.com/datafuselabs/databend-jdbc/pull/179
- fix: check state https://github.com/datafuselabs/databend-jdbc/pull/178
close https://github.com/datafuselabs/databend-jdbc/issues/180

feat: release v0.2.1

---

databend-jdbc/src/main/java/com/databend/jdbc/DatabendConnection.java
databend-jdbc/src/main/java/com/databend/jdbc/cloud/DatabendPresignClientV1.java

- Add the fileSize and upload duration in upload stream

chore: add more upload failed log info

---

databend-jdbc/src/main/java/com/databend/jdbc/AbstractDatabendResultSet.java
databend-jdbc/src/main/java/com/databend/jdbc/DatabendResultSet.java
databend-jdbc/src/main/java/com/databend/jdbc/DatabendStatement.java

- add original SQL text in query failed exception

feat: add original SQL text in query failed exception

---

databend-client/src/main/java/com/databend/client/DatabendClient.java
databend-client/src/main/java/com/databend/client/DatabendClientV1.java
databend-client/src/main/java/com/databend/client/DatabendSession.java
databend-client/src/main/java/com/databend/client/ParseJsonDataUtils.java
databend-client/src/main/java/com/databend/client/QueryResults.java
databend-client/src/test/java/com/databend/client/TestClientIT.java
databend-client/src/test/java/com/databend/client/TestQueryAffect.java
databend-client/src/test/java/com/databend/client/TestQueryErrors.java
databend-client/src/test/java/com/databend/client/TestQueryResults.java
databend-jdbc/src/main/java/com/databend/jdbc/DatabendConnection.java
databend-jdbc/src/main/java/com/databend/jdbc/DatabendResultSet.java
databend-jdbc/src/main/java/com/databend/jdbc/DatabendStatement.java
databend-jdbc/src/test/java/com/databend/jdbc/TestBasicDriver.java
databend-jdbc/src/test/java/com/databend/jdbc/TestDatabendDatabaseMetaData.java
databend-jdbc/src/test/java/com/databend/jdbc/TestDatabendDriverUri.java

1. [refactor: DatabendSession hide irrelevant fields.](https://github.com/datafuselabs/databend-jdbc/commit/f2e19bfb99af2be0c6a0ec1859af9d3f23186fbe)
2. [close Client with /final instead of /kill.](https://github.com/datafuselabs/databend-jdbc/commit/17913acd2ab9cc369b3f39621cc7ee8c5ec5e20b)
3. [fix: check null for data and schema.](https://github.com/datafuselabs/databend-jdbc/commit/28631b087cb7c45d4703b66f0aa6310176a9c6c9)
4. [refactor: close query earlier.](https://github.com/datafuselabs/databend-jdbc/commit/67a15cd7865737252b65951f57b822c1c9bb02b9)

small refactors to DatabendClient.

---

README.md
databend-client/pom.xml
databend-jdbc/pom.xml
pom.xml

Feat:
- feat: add the type mapping docs https://github.com/datafuselabs/databend-jdbc/pull/194
- feat: some refactor for DatabendClient https://github.com/datafuselabs/databend-jdbc/pull/195
- feat: add original SQL text in query failed exception https://github.com/datafuselabs/databend-jdbc/pull/196
- feat: add debug flag in DSN https://github.com/datafuselabs/databend-jdbc/pull/200
- feat: add use_verify param in DSN feat: add connection param use_verify
Fix:
- fix: remove databaseTableName in BatchInsertUtils https://github.com/datafuselabs/databend-jdbc/pull/197

feat: release 0.2.3

---

databend-jdbc/src/test/java/com/databend/jdbc/TestBasicDriver.java

feat: add testCreateUserFunction

---

databend-jdbc/pom.xml
databend-jdbc/src/main/java/com/databend/jdbc/examples/DatabendConnectionFactory.java
databend-jdbc/src/main/java/com/databend/jdbc/examples/DatabendConnectionPool.java

Add an example to show how to implement a connection pool for DatabendConnection.

feat: add DatabendConnection pool factory examples

---

README.md
databend-client/pom.xml
databend-jdbc/pom.xml
pom.xml

close https://github.com/datafuselabs/databend-jdbc/issues/216

feat: release v0.2.6

---

databend-jdbc/src/main/java/com/databend/jdbc/DatabendConnection.java
databend-jdbc/src/test/java/com/databend/jdbc/TestDatabendDriverUri.java

Fix https://github.com/datafuselabs/databend-jdbc/issues/219

fix: connection setSchema to switch database

---

README.md
databend-client/pom.xml
databend-jdbc/pom.xml
pom.xml

release note: https://github.com/datafuselabs/databend-jdbc/issues/222

feat: release databend 0.2.7

---

databend-client/src/main/java/com/databend/client/DatabendClientV1.java
databend-client/src/main/java/com/databend/client/JsonResponse.java
databend-client/src/main/java/com/databend/client/data/Int8Handler.java
databend-jdbc/src/test/java/com/databend/jdbc/TestPrepareStatement.java

Fix `com.fasterxml.jackson.databind.exc.ValueInstantiationException: Cannot construct instance of com.databend.client.QueryResults, problem: For input string: "nan"` error

fix: handle nan data in response

---

databend-jdbc/src/main/java/com/databend/jdbc/AbstractDatabendResultSet.java

Fix https://github.com/datafuselabs/databend-jdbc/issues/232

fix: wasNull implement

---

databend-client/src/main/java/com/databend/client/ClientSettings.java
databend-client/src/main/java/com/databend/client/DatabendClientV1.java

To fix https://github.com/datafuselabs/databend-jdbc/issues/231

fix: error response field

---

databend-client/src/main/java/com/databend/client/data/ColumnTypeHandlerFactory.java
databend-client/src/main/java/com/databend/client/data/DatabendDataType.java
databend-client/src/main/java/com/databend/client/data/DatabendTypes.java
databend-client/src/main/java/com/databend/client/data/GeometryHandler.java
databend-client/src/test/java/com/databend/client/TestQueryResults.java
databend-client/src/test/java/com/databend/client/data/TestColumnTypeHandlerFactory.java
databend-client/src/test/java/com/databend/client/data/TestDatabendTypes.java
databend-jdbc/pom.xml
databend-jdbc/src/main/java/com/databend/jdbc/DatabendColumnInfo.java
databend-jdbc/src/test/java/com/databend/jdbc/TestBasicDriver.java

Issue link: https://github.com/datafuselabs/databend-jdbc/issues/240

Support geometry type for jdbc

---

databend-jdbc/src/main/java/com/databend/jdbc/DatabendDatabaseMetaData.java

To get table and view DDL in DBeaver contribution, need to include the catalog  e.g. SHOW CREATE TABLE my_db.table1

Switch flags for support catalog in DDL/DML

---

databend-client/src/main/java/com/databend/client/ClientSettings.java
databend-client/src/main/java/com/databend/client/DatabendClientV1.java
databend-client/src/main/java/com/databend/client/DatabendSession.java
databend-jdbc/src/main/java/com/databend/jdbc/ConnectionProperties.java
databend-jdbc/src/main/java/com/databend/jdbc/DatabendConnection.java
databend-jdbc/src/main/java/com/databend/jdbc/DatabendDriverUri.java

Add route hint header support.

feat: add route hint support

---

databend-jdbc/src/main/java/com/databend/jdbc/DatabendConnection.java
databend-jdbc/src/main/java/com/databend/jdbc/DatabendDriverUri.java
databend-jdbc/src/main/java/com/databend/jdbc/URLUtils.java
databend-jdbc/src/test/java/com/databend/jdbc/TestFileTransfer.java
databend-jdbc/src/test/java/com/databend/jdbc/TestPrepareStatement.java

Fix https://github.com/datafuselabs/databend-jdbc/issues/236

fix: encode speacial char in password

---

databend-jdbc/src/main/java/com/databend/jdbc/DatabendDatabaseMetaData.java

Fix https://github.com/datafuselabs/databend-jdbc/issues/247

fix: stringColumnLike

---

README.md
databend-client/pom.xml
databend-jdbc/pom.xml
pom.xml

fixes: https://github.com/datafuselabs/databend-jdbc/issues/258

feat: release 0.2.9

---

README.md

1. Support Client Side Load Balancing Auto Discovery, [doc](https://github.com/datafuselabs/databend-jdbc/blob/main/docs/Connection.md#automatic-node-discovery)
2. Fix Transaction issue on client side load balancing

feat: release databend v0.3.1

---

databend-jdbc/src/main/java/com/databend/jdbc/PresignContext.java

chore: make getPresignContext throw a clear err msg

---

.github/actions/setup_databend_cluster/action.yml
.github/workflows/test_cluster.yml
databend-client/src/main/java/com/databend/client/DatabendClient.java
databend-client/src/main/java/com/databend/client/DatabendClientFactory.java
databend-client/src/main/java/com/databend/client/DatabendClientV1.java
databend-client/src/main/java/com/databend/client/JsonCodec.java
databend-client/src/main/java/com/databend/client/JsonResponse.java
databend-client/src/main/java/com/databend/client/OkHttpUtils.java
databend-client/src/main/java/com/databend/client/QueryResults.java
databend-client/src/main/java/com/databend/client/QuerySchema.java
databend-client/src/main/java/com/databend/client/ServerInfo.java
databend-client/src/test/java/com/databend/client/TestClientIT.java
databend-client/src/test/java/com/databend/client/TestDiscoveryNodes.java
databend-client/src/test/java/com/databend/client/TestQueryAffect.java
databend-client/src/test/java/com/databend/client/TestQueryResults.java
databend-jdbc/src/main/java/com/databend/jdbc/AbstractDatabendResultSet.java
databend-jdbc/src/main/java/com/databend/jdbc/DatabendConnection.java
databend-jdbc/src/main/java/com/databend/jdbc/DatabendDriverUri.java
databend-jdbc/src/main/java/com/databend/jdbc/DatabendNodes.java
databend-jdbc/src/main/java/com/databend/jdbc/DatabendResultSet.java
databend-jdbc/src/main/java/com/databend/jdbc/DatabendStatement.java
databend-jdbc/src/main/java/com/databend/jdbc/NonRegisteringDatabendDriver.java

Reverts databendlabs/databend-jdbc#287
com.databend.client is in use, can not change the name of public classes

Revert "refactor: move/rename some class"

---

databend-client/src/main/java/com/databend/client/ParseJsonDataUtils.java
databend-client/src/main/java/com/databend/client/QueryResults.java
databend-client/src/main/java/com/databend/client/data/ColumnTypeHandler.java
databend-client/src/main/java/com/databend/client/data/ColumnTypeHandlerBase.java
databend-client/src/main/java/com/databend/client/data/GeometryHandler.java
databend-client/src/main/java/com/databend/client/data/Int8Handler.java
databend-client/src/main/java/com/databend/client/data/StringHandler.java
databend-jdbc/src/main/java/com/databend/jdbc/AbstractDatabendResultSet.java

and add `getDataRaw` to use in TTC test

refactor: simplify data decoder.

---

databend-jdbc/src/main/java/com/databend/jdbc/cloud/DatabendPresignClientV1.java

- Add more logs in uploadStream presign stage
- add ` contentLength()` in requst
- http config when do presign

feat: enhance stream upload

---

databend-jdbc/src/main/java/com/databend/jdbc/DatabendConnection.java
databend-jdbc/src/test/java/com/databend/jdbc/TestPrepareStatement.java

Fix java.lang.RuntimeException: Failed to create FileHandler

fix: failed to handle FileHandler

---

databend-client/src/main/java/com/databend/client/QueryStats.java
databend-jdbc/src/main/java/com/databend/jdbc/DatabendPreparedStatement.java
databend-jdbc/src/main/java/com/databend/jdbc/DatabendStatement.java
databend-jdbc/src/test/java/com/databend/jdbc/TestBasicDriver.java
databend-jdbc/src/test/java/com/databend/jdbc/TestPrepareStatement.java

Get the affect count from result data, not from the progress.

fix: the return count of executeUpdate

---

README.md
databend-client/src/main/java/com/databend/client/DatabendClientV1.java
databend-client/src/main/java/com/databend/client/ServerInfo.java
databend-client/src/main/java/com/databend/client/constant/DatabendConstant.java
databend-client/src/main/java/com/databend/client/data/ColumnTypeHandlerBase.java
databend-client/src/main/java/com/databend/client/data/Int8Handler.java
databend-jdbc/src/main/java/com/databend/jdbc/AbstractDatabendResultSet.java
databend-jdbc/src/main/java/com/databend/jdbc/DatabendConnection.java
databend-jdbc/src/main/java/com/databend/jdbc/DatabendDatabaseMetaData.java
databend-jdbc/src/main/java/com/databend/jdbc/DatabendDriverUri.java
databend-jdbc/src/main/java/com/databend/jdbc/DatabendPreparedStatement.java
databend-jdbc/src/main/java/com/databend/jdbc/DatabendResultSet.java
databend-jdbc/src/main/java/com/databend/jdbc/cloud/DatabendStage.java
databend-jdbc/src/main/java/com/databend/jdbc/constant/DatabendConstant.java
databend-jdbc/src/main/java/com/databend/jdbc/util/URLUtils.java
pom.xml

1.solve all blocking issue of alibaba coding guidelines
2.add constant & util folder to place common constants or utils
3.update README.md & pom.xml

feat: project structure and docs maintenance

---

.github/workflows/test_cluster.yml
databend-jdbc/src/main/java/com/databend/jdbc/AbstractDatabendResultSet.java
databend-jdbc/src/test/java/com/databend/jdbc/TestBasicDriver.java
databend-jdbc/src/test/java/com/databend/jdbc/TestPrepareStatement.java

1. create a table : create table test_basic_driver.table_with_null(a int,b varchar default null, c varchar, d varchar)
2. insert values: insert into test_basic_driver.table_with_null(a,b,c,d) values(1,null,'null','NULL')
3. should return `1, null, 'null', 'NULL'`

fix: null value and add tests
