databendlabs/databend-jdbc

databend-jdbc/src/main/java/com/databend/jdbc/DatabendConnection.java
to avoid server side from waiting for timeout.
https://stackoverflow.com/questions/4507440/must-jdbc-resultsets-and-statements-be-closed-separately-although-the-connection
=> close statements when closing conn.

pom.xml
Linked issue https://github.com/databendcloud/databend-jdbc/issues/87
Rename jackson package to `com.databend.jdbc.com.fasterxml.jackson.*`
=> Fix jackson package conflict problem

databend-client/src/main/java/com/databend/client/data/Int8Handler.java
If a column's type is boolean, databend-jdbc will always return `false`.
The reason for this bug has been found so far is because the boolean type data returned via databend is either "1" or "0" and can never be true via a conversion by `Boolean.parseBoolean((String) value)`.
Now fix this problem, only `true` if the returned data is "true" or "1", other types of string data are `false`.
=> Fix conversion error when boolean type is returned as string

databend-jdbc/src/main/java/com/databend/jdbc/DatabendDatabaseMetaData.java
Issue: https://github.com/databendcloud/databend-jdbc/issues/83
Enable the close statement method at the same time we close the resultset, so that the connection can reclaim unused statements.
=> Close Statement when ResultSet that returned in DatabendDatabaseMetaData is closing

databend-jdbc/src/main/java/com/databend/jdbc/DatabendDatabaseMetaData.java, databend-jdbc/src/main/java/com/databend/jdbc/DatabendUnboundQueryResultSet.java, databend-jdbc/src/test/java/com/databend/jdbc/TestDatabendDatabaseMetaData.java
Issue: https://github.com/databendcloud/databend-jdbc/issues/86
Current conversion:
* `TABLE`(Jdbc) -> `BASE TABLE`(Databend)
* `SYSTEM VIEW`(Jdbc) to `SYSTEM TABLE`(Databend)
Meanwhile, the implementation of `getTableTypes` method has been changed to return a fixed result, and MySQL JDBC is as consistent as possible.
=> Convert TABLE_TYPE to jdbc standard type

databend-jdbc/src/main/java/com/databend/jdbc/DatabendConnection.java
When use Druild create jdbc pool this will cause null point exception.
=> fix: fix prepareCall

databend-client/src/main/java/com/databend/client/data/DatabendDataType.java, databend-client/src/main/java/com/databend/client/data/DatabendRawType.java, databend-client/src/main/java/com/databend/client/data/DatabendTypes.java, databend-client/src/test/java/com/databend/client/data/TestColumnTypeHandlerFactory.java, databend-client/src/test/java/com/databend/client/data/TestDatabendTypes.java, databend-jdbc/src/main/java/com/databend/jdbc/DatabendDatabaseMetaData.java, databend-jdbc/src/test/java/com/databend/jdbc/TestDatabendDatabaseMetaData.java
Issue link: https://github.com/datafuselabs/databend-jdbc/issues/82
Main changes:
* Converts `DATA_TYPE` to int, some code references on PR https://github.com/datafuselabs/databend-jdbc/pull/85 .
* Fixed the `Nullable` parsing error in nested types such as `Tuple`.
* Added and improved some missing data types, such as `Tuple`,`Map`, etc.
* Reformat the `DatabendDatabaseMetaData`, `{` not to wrap, to unified code specification as possible.
* Also fixed several other bugs listed in issue https://github.com/datafuselabs/databend-jdbc/issues/84
=> Fixed an issue with the DATA_TYPE field returning the wrong type in DatabendDatabaseMetaData

databend-jdbc/pom.xml, databend-jdbc/src/main/java/com/databend/jdbc/DatabendPreparedStatement.java, databend-jdbc/src/main/java/com/databend/jdbc/LoggerUtil.java, databend-jdbc/src/main/java/com/databend/jdbc/NonQueryRawStatement.java, databend-jdbc/src/main/java/com/databend/jdbc/ParamMarker.java, databend-jdbc/src/main/java/com/databend/jdbc/QueryRawStatement.java, databend-jdbc/src/main/java/com/databend/jdbc/RawStatement.java, databend-jdbc/src/main/java/com/databend/jdbc/RawStatementWrapper.java, databend-jdbc/src/main/java/com/databend/jdbc/SetParamRawStatement.java, databend-jdbc/src/main/java/com/databend/jdbc/StatementInfoWrapper.java, databend-jdbc/src/main/java/com/databend/jdbc/StatementType.java, databend-jdbc/src/main/java/com/databend/jdbc/StatementUtil.java, databend-jdbc/src/main/java/com/databend/jdbc/log/DatabendLogger.java, databend-jdbc/src/main/java/com/databend/jdbc/log/JDKLogger.java, databend-jdbc/src/main/java/com/databend/jdbc/log/SLF4JLogger.java, databend-jdbc/src/main/java/com/databend/jdbc/parser/BatchInsertUtils.java, databend-jdbc/src/test/java/com/databend/jdbc/StatementUtilTest.java, databend-jdbc/src/test/java/com/databend/jdbc/TestBasicDriver.java, databend-jdbc/src/test/java/com/databend/jdbc/TestPrepareStatement.java, lombok.config
Fix https://github.com/datafuselabs/databend-jdbc/issues/104
=> feat: impl prepareStatement method

databend-jdbc/src/main/java/com/databend/jdbc/DatabendPreparedStatement.java, databend-jdbc/src/test/java/com/databend/jdbc/TestPrepareStatement.java
- Fix `executeUpdate` not wait sql executing bug
=> fix: executeUpdate bug

databend-client/pom.xml, databend-jdbc/pom.xml, pom.xml
1. fix update race condition during high concurrency
2. add more examples around dml operations using databend jdbc [ example link](https://github.com/datafuselabs/databend-jdbc/tree/main/databend-jdbc/src/main/java/com/databend/jdbc/examples)
3. several bug fixes [104](https://github.com/datafuselabs/databend-jdbc/issues/104), [102](https://github.com/datafuselabs/databend-jdbc/issues/102)
=> feat: release databend-jdbc v0.1.4

databend-jdbc/src/main/java/com/databend/jdbc/DatabendColumnInfo.java
`DatabendRawType` is a class object, and the `toString()` method does not get the type name of the object itself.
=> Fix column type name error for DatabendRawType

databend-jdbc/pom.xml, databend-jdbc/src/main/java/com/databend/jdbc/AbstractDatabendResultSet.java, databend-jdbc/src/main/java/com/databend/jdbc/DatabendPreparedStatement.java, databend-jdbc/src/main/java/com/databend/jdbc/parser/BatchInsertUtils.java, databend-jdbc/src/test/java/com/databend/jdbc/TestPrepareStatement.java, pom.xml
Databend use `\N` as default null representation for csv and tsv format, which fixes https://github.com/datafuselabs/databend/issues/5586.
So we make `setNull` with `\N`.
=> fix: setNull with \N

databend-jdbc/src/main/java/com/databend/jdbc/DatabendColumnInfo.java, databend-jdbc/src/main/java/com/databend/jdbc/DatabendResultSetMetaData.java, databend-jdbc/src/test/java/com/databend/jdbc/TestDatabendDatabaseMetaData.java
Fix bug when `rs.getMetaData().getColumnType` for decimal(x,y) type failed.
=> fix: resultSetMetadata get decimal column

databend-jdbc/src/main/java/com/databend/jdbc/DatabendStatement.java
Because `insert into` single data will return non-empty `schema` field, this cause `final` api not called.
=> fix: insert into single data then close query auto

databend-jdbc/src/main/java/com/databend/jdbc/DatabendConnection.java, databend-jdbc/src/main/java/com/databend/jdbc/PresignContext.java
Use `RuntimeException` instead of `JsonProcessingException` in uploadStream.
=> fix: uploadStream exception

databend-jdbc/src/main/java/com/databend/jdbc/DatabendPreparedStatement.java, databend-jdbc/src/test/java/com/databend/jdbc/TestBasicDriver.java
Now select with preparement will cause an error like :
This pr fix it.
=> fix: select with preparement for timestamp

.github/workflows/test.yml, databend-jdbc/src/main/java/com/databend/jdbc/DatabendDatabaseMetaData.java, databend-jdbc/src/test/java/com/databend/jdbc/TestDatabendDatabaseMetaData.java
Just match RegEx in Full string "Databend Query vx.y.zzz" or "DatabendQuery vx.y.zzz"
Fixes https://github.com/datafuselabs/databend-jdbc/issues/204
=> Fix getDatabaseMajorVersion & getDatabaseMinorVersion

databend-jdbc/src/main/java/com/databend/jdbc/DatabendDatabaseMetaData.java, databend-jdbc/src/main/java/com/databend/jdbc/cloud/DatabendPresignClientV1.java, databend-jdbc/src/test/java/com/databend/jdbc/TestBasicDriver.java, databend-jdbc/src/test/java/com/databend/jdbc/TestFileTransfer.java
- try to fix `error is java.net.ProtocolException: expected 2147483647 bytes but received 2147483648` 
- add more tests
=> fix: uploadStream over 2Gi failed

databend-jdbc/src/main/java/com/databend/jdbc/DatabendDatabaseMetaData.java, databend-jdbc/src/test/java/com/databend/jdbc/TestBasicDriver.java, databend-jdbc/src/test/java/com/databend/jdbc/TestDatabendDatabaseMetaData.java
Linked issue: https://github.com/datafuselabs/databend-jdbc/issues/261
=> Add view list for metadata getTables method

.github/actions/setup_databend_cluster/action.yml, .github/workflows/test_cluster.yml, databend-client/src/main/java/com/databend/client/DatabendSession.java, databend-client/src/main/java/com/databend/client/GlobalCookieJar.java, databend-jdbc/src/main/java/com/databend/jdbc/DatabendConnection.java, databend-jdbc/src/main/java/com/databend/jdbc/DatabendDriverUri.java, databend-jdbc/src/main/java/com/databend/jdbc/NonRegisteringDatabendDriver.java, databend-jdbc/src/test/java/com/databend/jdbc/TestTempTable.java
temp table have states across query at the server side, need:
1. session id: carried in cookie
2. logout: to clean up the states
after this pr, temp table is available, require databend server version >= 1.2.655 , but since heartbeat is not implemented yet, temp table will be cleaned up after session is idle for 4 hours, it is recommended to drop temp table after use, vacuum is used incase of forget or fail to drop it
unlike https://github.com/databendlabs/bendsql/pull/479, session token is not introduced in the same pr, as it may need bigger refactor
=> feat: support temp table.

.github/actions/setup_databend_cluster/action.yml, .github/workflows/test_cluster.yml, databend-jdbc/src/main/java/com/databend/jdbc/cloud/DatabendPresignClientV1.java
The presigned url is sensitive so we need remove it from log.
=> fix: remove presigned url in log

databend-jdbc/src/main/java/com/databend/jdbc/DatabendDriverUri.java
Now empty password will get such errors:
```
Caused by: java.lang.RuntimeException: Query failed: QueryErrors{code=5100, message=No authorization header detected} 
```
=> fix: empty password error

databend-client/src/main/java/com/databend/client/ClientSettings.java, databend-jdbc/src/main/java/com/databend/jdbc/ConnectionProperties.java, databend-jdbc/src/main/java/com/databend/jdbc/DatabendConnection.java, databend-jdbc/src/main/java/com/databend/jdbc/DatabendDriverUri.java, databend-jdbc/src/test/java/com/databend/jdbc/TestDatabendDriverUri.java
use case:
```java
Properties props = new Properties();
props.setProperty("session_settings", "key1=value1,key2=value2");
Connection conn = DriverManager.getConnection("jdbc:databend://host:port/database", props);
```
=> feat: support session settings in properties

databend-client/src/test/java/com/databend/client/TestClientIT.java, databend-jdbc/src/main/java/com/databend/jdbc/DatabendConnection.java, databend-jdbc/src/main/java/com/databend/jdbc/DatabendPreparedStatement.java, databend-jdbc/src/main/java/com/databend/jdbc/StatementInfoWrapper.java, databend-jdbc/src/main/java/com/databend/jdbc/StatementUtil.java, databend-jdbc/src/main/java/com/databend/jdbc/parser/BatchInsertUtils.java
Because the query-id format in databend query will be changed from `a-b-c-d` to `abcd` in this https://github.com/databendlabs/databend/pull/17947, so the jdbc need to do the same. 
We change the code where generate query-id.
This pr should be merged after the databend query make compatibility.
=> feat: re-format the query-id

databend-client/src/main/java/com/databend/client/ClientSettings.java, databend-client/src/main/java/com/databend/client/DatabendClientV1.java, databend-client/src/main/java/com/databend/client/ParseJsonDataUtils.java, databend-jdbc/src/main/java/com/databend/jdbc/AbstractDatabendResultSet.java, databend-jdbc/src/main/java/com/databend/jdbc/DatabendClientLoadBalancingPolicy.java, databend-jdbc/src/main/java/com/databend/jdbc/DatabendColumnInfo.java, databend-jdbc/src/main/java/com/databend/jdbc/DatabendDatabaseMetaData.java, databend-jdbc/src/main/java/com/databend/jdbc/DatabendDriverUri.java, databend-jdbc/src/main/java/com/databend/jdbc/DatabendPreparedStatement.java, databend-jdbc/src/main/java/com/databend/jdbc/DatabendResultSet.java, databend-jdbc/src/main/java/com/databend/jdbc/DatabendStatement.java, databend-jdbc/src/main/java/com/databend/jdbc/ParamMarker.java, databend-jdbc/src/main/java/com/databend/jdbc/StatementType.java, databend-jdbc/src/main/java/com/databend/jdbc/StatementUtil.java, databend-jdbc/src/main/java/com/databend/jdbc/cloud/DatabendCopyParams.java, databend-jdbc/src/main/java/com/databend/jdbc/cloud/DatabendPresignClientV1.java, databend-jdbc/src/main/java/com/databend/jdbc/constant/DatabendConstant.java, databend-jdbc/src/main/java/com/databend/jdbc/examples/DatabendConnectionPool.java
1.remove useless try-finally
2.Do not use end-of-line comments.
3.add DatabendConstant
4.parameters should name ignore or ignored when catch block is null (from Qodana)
=> feat: remove useless try-finally, etc.
